[build]
builder = "NIXPACKS"
buildCommand = "npm install --legacy-peer-deps && npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
NODE_ENV = "production"
SESSION = "M_D"
PREFIX = "!"
NAME = "M_D BOT"
